#!/bin/bash

TS_TOPDIR="${0%/*}/../.."
TS_DESC="listmount"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MOUNT"
ts_check_test_command "$TS_CMD_UMOUNT"

ts_skip_nonroot

TESTPROG="$TS_HELPER_LIBMOUNT_LISTMOUNT"

[ -x $TESTPROG ] || ts_skip "test not compiled"

ts_init_subtest "listmount-tmpfs"
# Create directories
for i in $(seq 1 2000); do
    mkdir -p "listmount-tmpfs$i"
done

for i in $(seq 1 2000); do
    $TS_CMD_MOUNT -t tmpfs none "listmount-tmpfs$i"
done

$TESTPROG

for i in $(seq 1 2000); do
    $TS_CMD_UMOUNT "listmount-tmpfs$i"
    rmdir "listmount-tmpfs$i"
done
ts_log "Success"
ts_finalize_subtest

ts_finalize
