#!/bin/bash

TS_TOPDIR="${0%/*}/../.."
TS_DESC="statmount"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_MOUNT"
ts_check_test_command "$TS_CMD_UMOUNT"

ts_skip_nonroot

TESTPROG="$TS_HELPER_LIBMOUNT_STATMOUNT"

[ -x $TESTPROG ] || ts_skip "test not compiled"

ts_init_subtest "statmount-tmpfs"
mkdir -p "statmount-tmpfs"
$TS_CMD_MOUNT -t tmpfs none "statmount-tmpfs"

$TESTPROG $PWD/statmount-tmpfs >> $TS_OUTPUT 2>> $TS_ERRLOG

sed -i 's/target: .*/target: ?/g' $TS_OUTPUT
sed -i 's/id: .*/id: ?/g' $TS_OUTPUT
sed -i 's/parent: .*/parent: ?/g' $TS_OUTPUT
sed -i 's/uniq-id: .*/uniq-id: ?/g' $TS_OUTPUT
sed -i 's/uniq-parent: .*/uniq-parent: ?/g' $TS_OUTPUT
sed -i 's/devno: .*/devno: ?/g' $TS_OUTPUT
sed -i 's/[[:space:]]*$//' $TS_OUTPUT

$TS_CMD_UMOUNT "statmount-tmpfs"
rmdir "statmount-tmpfs"
ts_finalize_subtest

ts_finalize
